[tasks.clean-app]
run_task = [
    {name = ["clean-backend", "clean-tauri"]}
]

[tasks.clean-backend]
cwd = "./BYBE-tauri/BYBE-backend/"
command = "cargo"
args = ["clean"]

[tasks.clean-tauri]
cwd = "./BYBE-tauri/"
command = "cargo"
args = ["clean"]

[tasks.be_build]
cwd = "./BYBE-tauri/BYBE-backend/"
command = "cargo"
args = ["make", "bybe-release"]

[tasks.prepare_be]
cwd = "./BYBE-tauri/BYBE-backend/"
command = "cargo"
args = ["make", "prebuild"]

[tasks.post_build]
cwd = "./BYBE-tauri/BYBE-backend/"
command = "cargo"
args = ["make", "post_build"]

[tasks.build]
install_crate = "tauri-cli"
command = "cargo"
args = ["tauri", "build"]
dependencies = ["clean-app", "prepare_be"]

[tasks.build-multiplat-app]
dependencies = ["build"]

[tasks.build-linux-app]
dependencies = ["build"]
env = { NO_STRIP=true }

[tasks.build-app]
run_task = [
    { name = "build-multiplat-app", condition = { platforms = ["windows", "mac"]} },
    { name = "build-linux-app", condition = { platforms = ["linux"]} },
]
